<a href="https://colab.research.google.com/github/mmtog/Regresi-n-Log-stica/blob/main/regre_log.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [422]:
#Cargamos librerias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [388]:
grecia =pd.read_csv("Grecia_limpios_final.csv")
grecia.head(5)

Unnamed: 0  host_total_listings_count  accommodates  price  minimum_nights  \
0           0                       10.0           3.5  108.0             1.0   
1           1                       10.0           4.0  136.0             1.0   
2           2                       10.0           2.0   67.0             1.0   
3           3                       10.0           4.0   78.0             1.0   
4           4                       10.0           2.0   58.0             1.0   

   maximum_nights  minimum_minimum_nights  maximum_minimum_nights  \
0           180.0                     1.0                     4.0   
1          1125.0                     1.0                     4.0   
2            90.0                     1.0                     3.0   
3            45.0                     1.0                     3.0   
4          1125.0                     1.0                     4.0   

   minimum_maximum_nights  maximum_maximum_nights  ...  \
0                   180.0                   180.0  ...   
1                  1125.0                  1125.0  ...   
2                    90.0                    90.0  ...   
3                    45.0                    45.0  ...   
4                  1125.0                  1125.0  ...   

   host_identity_verified  neighbourhood_cleansed       property_type  \
0                       t             ΑΜΠΕΛΟΚΗΠΟΙ        Entire condo   
1                       t             ΑΜΠΕΛΟΚΗΠΟΙ  Entire rental unit   
2                       t             ΑΜΠΕΛΟΚΗΠΟΙ  Entire rental unit   
3                       t             ΑΜΠΕΛΟΚΗΠΟΙ  Entire rental unit   
4                       t             ΑΜΠΕΛΟΚΗΠΟΙ  Entire rental unit   

         room_type  bathrooms  bedrooms  \
0  Entire home/apt        2.0       3.0   
1  Entire home/apt        1.0       1.0   
2  Entire home/apt        1.0       0.0   
3  Entire home/apt        1.0       1.0   
4  Entire home/apt        1.0       1.0   

                                           amenities  calendar_last_scraped  \
0  ["Ethernet connection", "Room-darkening shades...             2024-06-26   
1  ["Ethernet connection", "43 inch HDTV", "Priva...             2024-06-26   
2  ["Ethernet connection", "43 inch HDTV", "Priva...             2024-06-26   
3  ["Ethernet connection", "Private patio or balc...             2024-06-26   
4  ["Other electric stove", "Room-darkening shade...             2024-06-26   

      id  host_id  
0  10595    37177  
1  10990    37177  
2  10993    37177  
3  10995    37177  
4  27262    37177  

[5 rows x 44 columns]

In [ ]:
# Reemplazar 'unknown' por NaN
grecia['bathrooms'] = grecia['bathrooms'].replace('Unknown', np.nan)
grecia['bedrooms'] = grecia['bedrooms'].replace('Unknown', np.nan)
# convertir a float
grecia['bathrooms'] = grecia['bathrooms'].astype(float)
grecia['bedrooms'] = grecia['bedrooms'].astype(float)

In [ ]:
#Rellenamos valores nulos
grecia= grecia.fillna(method='bfill')
greciaf= grecia.fillna(method='ffill')

<ipython-input-8-fd68f459e81f>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  grecia= grecia.fillna(method='bfill')
<ipython-input-8-fd68f459e81f>:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  greciaf= grecia.fillna(method='ffill')


In [ ]:
grecia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13274 entries, 0 to 13273
Data columns (total 44 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Unnamed: 0                 13274 non-null  int64  
 1   host_total_listings_count  13274 non-null  float64
 2   accommodates               13274 non-null  float64
 3   price                      13274 non-null  float64
 4   minimum_nights             13274 non-null  float64
 5   maximum_nights             13274 non-null  float64
 6   minimum_minimum_nights     13274 non-null  float64
 7   maximum_minimum_nights     13274 non-null  float64
 8   minimum_maximum_nights     13274 non-null  float64
 9   maximum_maximum_nights     13274 non-null  float64
 10  minimum_nights_avg_ntm     13274 non-null  float64
 11  maximum_nights_avg_ntm     13274 non-null  float64
 12  availability_30            13274 non-null  int64  
 13  availability_60            13274 non-null  int

In [ ]:
grecia['minimum_nights'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 13274 entries, 0 to 13273
Series name: minimum_nights
Non-Null Count  Dtype  
--------------  -----  
13274 non-null  float64
dtypes: float64(1)
memory usage: 103.8 KB


#** Regre Log 1 **



In [ ]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=grecia['minimum_nights'].max()
Min=grecia['minimum_nights'].min()
Limites= [Min, Max]
Limites

[1.0, 3.0]

In [ ]:
#Categorización de variables
#Declaramos 2 intervalos
intervalos=np.linspace(.99, 3.1, 3)
intervalos

array([0.99 , 2.045, 3.1  ])

In [ ]:
#Creamos las categorías
categorias= ["visit", "vacation"]

In [ ]:
#Finalmente creamos las categorías en la columna numérica
grecia['minimum_nights']=pd.cut(x= grecia['minimum_nights'], bins=intervalos, labels= categorias )

In [ ]:
#Rellenamos valores nulos
grecia= grecia.fillna(method='bfill')
greciaf= grecia.fillna(method='ffill')

<ipython-input-145-fd68f459e81f>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  grecia= grecia.fillna(method='bfill')
<ipython-input-145-fd68f459e81f>:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  greciaf= grecia.fillna(method='ffill')


In [ ]:
grecia['minimum_nights'].isnull().sum()

0

In [ ]:
nulos= grecia.isnull().sum().sum()
nulos

0

In [ ]:
vars_Indep = grecia[['bathrooms']]
vars_Dep = grecia ['minimum_nights']

In [ ]:
#Redefinimos las variables
x= vars_Indep
y= vars_Dep

In [ ]:
#dividimos el conjunto de datos en la parte de entrenamiento y pruba
X_test, X_train, Y_test, Y_train= train_test_split(x,y, test_size=0.3, random_state=None)

In [ ]:
escalar = StandardScaler()

In [ ]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, Utilizaremos
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train, Y_train)

LogisticRegression()

In [ ]:
#realizamos una prediccion
y_pred = algoritmo.predict(X_test)
y_pred

array(['visit', 'visit', 'visit', ..., 'visit', 'visit', 'visit'],
      dtype=object)

In [ ]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(Y_test, y_pred)
print('Matriz de Confusion')
print(matriz)

Matriz de Confusion
[[   0 1106]
 [   1 8184]]


In [ ]:
#calculamos la prediccion del modelo
from sklearn.metrics import precision_score

precision = precision_score(Y_test, y_pred, average="binary", pos_label="visit")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.8809472551130247


In [ ]:
#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(Y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.880852437843074


In [ ]:
#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(Y_test, y_pred, average="binary", pos_label="visit")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.9998778252901649


# **2**

In [ ]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=grecia['review_scores_cleanliness'].max()
Min=grecia['review_scores_cleanliness'].min()
Limites= [Min, Max]
Limites

[3.78, 5.0]

In [ ]:
#Categorización de variables
#Declaramos 2 intervalos
intervalos1=np.linspace(3.77, 5.1,3)
intervalos1

array([3.77 , 4.435, 5.1  ])

In [ ]:
#Creamos las categorías
categorias1= ["sucio", "limpio"]

In [ ]:
grecia['review_scores_cleanliness']

0        4.85
1        4.86
2        4.94
3        4.90
4        4.96
         ... 
13269    4.80
13270    4.80
13271    4.80
13272    4.80
13273    4.80
Name: review_scores_cleanliness, Length: 13274, dtype: float64

In [ ]:
#Finalmente creamos las categorías en la columna numérica
grecia['review_scores_cleanliness']=pd.cut(x= grecia['review_scores_cleanliness'], bins=intervalos1, labels= categorias1 )

In [ ]:
#Rellenamos valores nulos
grecia= grecia.fillna(method='bfill')
grecia= grecia.fillna(method='ffill')

<ipython-input-169-8660068a4c2f>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  grecia= grecia.fillna(method='bfill')
<ipython-input-169-8660068a4c2f>:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  grecia= grecia.fillna(method='ffill')


In [ ]:
grecia['review_scores_cleanliness'].isnull().sum()

0

In [ ]:
vars_Indep_1 = grecia[['bedrooms']]
vars_Dep_1 = grecia['review_scores_cleanliness']

In [ ]:
#Redefinimos las variables
x= vars_Indep_1
y= vars_Dep_1

In [ ]:
#dividimos el conjunto de datos en la parte de entrenamiento y pruba
X_test1, X_train1, Y_test1, Y_train1= train_test_split(x,y, test_size=0.3, random_state=None)

In [ ]:
escalar1 = StandardScaler()

In [ ]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, Utilizaremos
X_train1 = escalar.fit_transform(X_train1)
X_test1 = escalar.transform(X_test1)

In [ ]:
#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo1 = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo1.fit(X_train1, Y_train1)

LogisticRegression()

In [ ]:
#realizamos una prediccion
y_pred1 = algoritmo1.predict(X_test1)
y_pred1

array(['limpio', 'limpio', 'limpio', ..., 'limpio', 'limpio', 'limpio'],
      dtype=object)

In [ ]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(Y_test1, y_pred1)
print('Matriz de Confusion')
print(matriz)

Matriz de Confusion
[[8686    0]
 [ 605    0]]


In [ ]:
#Calculamos la prediccion del modelo
from sklearn.metrics import precision_score

precision = precision_score(Y_test1, y_pred1, average="binary", pos_label="limpio")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.9348832203207404


In [ ]:
#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(Y_test1, y_pred1)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.9348832203207404


In [ ]:
#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(Y_test1, y_pred1, average="binary", pos_label="limpio")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
1.0


## **3**

In [ ]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=grecia['accommodates'].max()
Min=grecia['accommodates'].min()
Limites= [Min, Max]
Limites

[1.0, 7.0]

In [ ]:
#Categorización de variables
#Declaramos 2 intervalos
intervalos2=np.linspace(.99,7.1,3)
intervalos2

array([0.99 , 4.045, 7.1  ])

In [ ]:
#Creamos las categorías
categorias2= ["incomodo", "comodo"]

In [ ]:
grecia['accommodates']

0        3.5
1        4.0
2        2.0
3        4.0
4        2.0
        ... 
13269    4.0
13270    2.0
13271    2.0
13272    2.0
13273    2.0
Name: accommodates, Length: 13274, dtype: float64

In [ ]:
#Finalmente creamos las categorías en la columna numérica
grecia['accommodates']=pd.cut(x= grecia['accommodates'], bins=intervalos2, labels= categorias2 )

In [ ]:
#Rellenamos valores nulos
grecia= grecia.fillna(method='bfill')
greciaf= grecia.fillna(method='ffill')

<ipython-input-189-fd68f459e81f>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  grecia= grecia.fillna(method='bfill')
<ipython-input-189-fd68f459e81f>:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  greciaf= grecia.fillna(method='ffill')


In [ ]:
grecia['accommodates'].isnull().sum()

0

In [ ]:
vars_Indep_2 = grecia[['bedrooms']]

vars_Dep_2 = grecia['accommodates']

In [ ]:
#Redefinimos las variables
x= vars_Indep_2
y= vars_Dep_2

In [ ]:
#dividimos el conjunto de datos en la parte de entrenamiento y pruba
X_test2, X_train2, Y_test2, Y_train2= train_test_split(x,y, test_size=0.3, random_state=None)

In [ ]:
escalar2 = StandardScaler()

In [ ]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, Utilizaremos
X_train2 = escalar.fit_transform(X_train2)
X_test2 = escalar.transform(X_test2)

In [ ]:
#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo2 = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo2.fit(X_train2, Y_train2)

LogisticRegression()

In [ ]:
#realizamos una prediccion
y_pred2 = algoritmo2.predict(X_test2)
y_pred2

array(['comodo', 'incomodo', 'incomodo', ..., 'incomodo', 'incomodo',
       'incomodo'], dtype=object)

In [ ]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(Y_test2, y_pred2)
print('Matriz de Confusion')
print(matriz)

Matriz de Confusion
[[ 334 1325]
 [ 332 7300]]


In [ ]:
#CAlculamos la prediccion del modelo
from sklearn.metrics import precision_score
precision = precision_score(Y_test2, y_pred2, average="binary", pos_label="incomodo")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.8463768115942029


In [ ]:
#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(Y_test2, y_pred2)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.8216553654073835


In [ ]:
#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(Y_test2, y_pred2, average="binary", pos_label="incomodo")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.9564989517819706


## **4**

In [ ]:
#Ajustar maximo de filas
pd.options.display.max_rows= None

In [ ]:
grecia['bathrooms'] = pd.to_numeric(grecia['bathrooms'], errors='coerce')

In [ ]:
grecia = grecia.dropna(subset=['price'])

In [ ]:
grecia['price'] = pd.to_numeric(grecia['price'], errors='coerce')

# Eliminar los valores que quedaron como NaN después de la conversión
grecia = grecia.dropna(subset=['price'])


In [ ]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max = grecia['price'].max()
Min = grecia['price'].min()
Limites = [Min, Max]
Limites

[11.0, 214.0]

In [ ]:
#Categorización de variables
#Declaramos 2 intervalos
intervalos3=np.linspace(10.9,214.1, 3)
intervalos3

array([ 10.9, 112.5, 214.1])

In [ ]:
#Creamos las categorías
categorias3= ["barato", "caro"]

In [ ]:
#Finalmente creamos las categorías en la columna numérica
grecia['price']=pd.cut(x= grecia['price'], bins=intervalos3, labels= categorias3 )

In [ ]:
#Rellenamos valores nulos
grecia= grecia.fillna(method='bfill')
grecia= grecia.fillna(method='ffill')

<ipython-input-325-8660068a4c2f>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  grecia= grecia.fillna(method='bfill')
<ipython-input-325-8660068a4c2f>:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  grecia= grecia.fillna(method='ffill')


In [ ]:
grecia['price'].isnull().sum()

0

In [ ]:
vars_Indep_3 = grecia[['bathrooms']]

vars_Dep_3 = grecia['price']

In [ ]:
#Redefinimos las variables
x= vars_Indep_3
y= vars_Dep_3

In [ ]:
#dividimos el conjunto de datos en la parte de entrenamiento y pruba
X_test3, X_train3, Y_test3, Y_train3= train_test_split(x,y, test_size=0.3, random_state=None)

In [ ]:
escalar3 = StandardScaler()

In [ ]:
X_train3 = escalar3.fit_transform(X_train3) # use escalar3 instead of escalar
X_test3 = escalar3.transform(X_test3) # use escalar3 instead of escalar

In [ ]:
#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo3 = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo3.fit(X_train3, Y_train3)

LogisticRegression()

In [ ]:
#realizamos una prediccion
y_pred3 = algoritmo3.predict(X_test3)
y_pred3

array(['barato', 'barato', 'barato', ..., 'barato', 'barato', 'barato'],
      dtype=object)

In [ ]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(Y_test3, y_pred3)
print('Matriz de Confusion')
print(matriz)

Matriz de Confusion
[[7485   20]
 [1784    2]]


In [ ]:
#CAlculamos la prediccion del modelo
from sklearn.metrics import precision_score
precision = precision_score(Y_test3, y_pred3, average="binary", pos_label="barato")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.80753047793721


In [ ]:
#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(Y_test3, y_pred3)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.8058336024109353


In [ ]:
#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(Y_test3, y_pred3, average="binary", pos_label="barato")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.9973351099267155


## **5**

In [390]:
#Obtenemos el limite superior y el límite inferior de la columna objetivo
Max=grecia['review_scores_rating'].max()
Min=grecia['review_scores_rating'].min()
Limites= [Min, Max]
Limites

[3.82, 5.0]

In [429]:
grecia['review_scores_rating']

0        bueno
1        bueno
2        bueno
3        bueno
4        bueno
5        bueno
6        bueno
7        bueno
8        bueno
9        bueno
10       bueno
11        malo
12       bueno
13       bueno
14       bueno
15       bueno
16       bueno
17       bueno
18       bueno
19       bueno
20       bueno
21       bueno
22       bueno
23       bueno
24       bueno
25       bueno
26       bueno
27       bueno
28       bueno
29       bueno
30       bueno
31       bueno
32       bueno
33       bueno
34       bueno
35       bueno
36       bueno
37       bueno
38       bueno
39       bueno
40       bueno
41        malo
42       bueno
43       bueno
44       bueno
45       bueno
46       bueno
47       bueno
48       bueno
49       bueno
50       bueno
51       bueno
52       bueno
53       bueno
54       bueno
55       bueno
56       bueno
57       bueno
58       bueno
59       bueno
60       bueno
61       bueno
62       bueno
63       bueno
64       bueno
65       bueno
66       bueno
67       bueno
68       bueno
69       bueno
70       bueno
71       bueno
72       bueno
73       bueno
74       bueno
75       bueno
76       bueno
77       bueno
78       bueno
79       bueno
80       bueno
81       bueno
82       bueno
83       bueno
84       bueno
85       bueno
86       bueno
87       bueno
88       bueno
89       bueno
90       bueno
91        malo
92       bueno
93       bueno
94       bueno
95       bueno
96       bueno
97       bueno
98       bueno
99       bueno
100      bueno
101      bueno
102      bueno
103      bueno
104      bueno
105      bueno
106      bueno
107      bueno
108      bueno
109      bueno
110      bueno
111      bueno
112      bueno
113      bueno
114      bueno
115      bueno
116      bueno
117      bueno
118      bueno
119      bueno
120      bueno
121      bueno
122      bueno
123      bueno
124      bueno
125      bueno
126      bueno
127      bueno
128      bueno
129      bueno
130      bueno
131      bueno
132      bueno
133      bueno
134      bueno
135      bueno
136      bueno
137      bueno
138       malo
139      bueno
140      bueno
141      bueno
142      bueno
143      bueno
144      bueno
145      bueno
146      bueno
147      bueno
148      bueno
149      bueno
150      bueno
151      bueno
152       malo
153      bueno
154      bueno
155      bueno
156      bueno
157      bueno
158      bueno
159      bueno
160      bueno
161      bueno
162      bueno
163      bueno
164      bueno
165      bueno
166      bueno
167      bueno
168      bueno
169      bueno
170      bueno
171      bueno
172      bueno
173      bueno
174      bueno
175      bueno
176       malo
177      bueno
178      bueno
179      bueno
180      bueno
181      bueno
182      bueno
183      bueno
184      bueno
185      bueno
186      bueno
187      bueno
188      bueno
189      bueno
190      bueno
191      bueno
192      bueno
193      bueno
194       malo
195      bueno
196      bueno
197      bueno
198      bueno
199       malo
200      bueno
201      bueno
202      bueno
203      bueno
204      bueno
205      bueno
206      bueno
207      bueno
208      bueno
209      bueno
210      bueno
211      bueno
212      bueno
213      bueno
214      bueno
215      bueno
216      bueno
217      bueno
218      bueno
219      bueno
220      bueno
221      bueno
222      bueno
223      bueno
224      bueno
225      bueno
226      bueno
227      bueno
228      bueno
229      bueno
230      bueno
231      bueno
232      bueno
233      bueno
234      bueno
235      bueno
236      bueno
237      bueno
238      bueno
239      bueno
240      bueno
241      bueno
242      bueno
243      bueno
244      bueno
245      bueno
246      bueno
247      bueno
248      bueno
249      bueno
250      bueno
251      bueno
252      bueno
253      bueno
254      bueno
255      bueno
256      bueno
257      bueno
258      bueno
259      bueno
260      bueno
261      bueno
262      bueno
263       malo
264      bueno
265      bueno
266      b

In [430]:
#Categorización de variables
#Declaramos 2 intervalos
intervalos4=np.linspace(3.83, 5.01, 3)
intervalos4

array([3.83, 4.42, 5.01])

In [431]:
#Creamos las categorías
categorias4= ["malo", "bueno"]

In [433]:
grecia['review_scores_rating'] = pd.to_numeric(grecia['review_scores_rating'], errors='coerce')

In [ ]:
#Finalmente creamos las categorías en la columna numérica
grecia['review_scores_rating']=pd.cut(x= grecia['review_scores_rating'], bins=intervalos4, labels= categorias4 )

In [395]:
#Rellenamos valores nulos
grecia= grecia.fillna(method='bfill')
grecia= grecia.fillna(method='ffill')

<ipython-input-395-8660068a4c2f>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  grecia= grecia.fillna(method='bfill')
<ipython-input-395-8660068a4c2f>:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  grecia= grecia.fillna(method='ffill')


In [407]:
grecia['review_scores_rating'].isnull().sum()

0

In [408]:
grecia['bedrooms'] = pd.to_numeric(grecia['bedrooms'], errors='coerce')

In [409]:
vars_Indep_4 = grecia[['bedrooms']]

vars_Dep_4 = grecia['review_scores_rating']

In [410]:
#Redefinimos las variables
x= vars_Indep_4
y= vars_Dep_4

In [411]:
#dividimos el conjunto de datos en la parte de entrenamiento y pruba
X_test4, X_train4, Y_test4, Y_train4= train_test_split(x,y, test_size=0.3, random_state=None)

In [412]:
escalar4 = StandardScaler()

In [413]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, Utilizaremos
X_train4 = escalar.fit_transform(X_train4)
X_test4 = escalar.transform(X_test4)

In [424]:
#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo4 = LogisticRegression()

In [425]:
#Entrenamos el modelo
algoritmo4.fit(X_train4, Y_train4)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [426]:
#Entrenamos el modelo
algoritmo4.fit(X_train4, Y_train4)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [427]:
#realizamos una prediccion
y_pred4 = algoritmo4.predict(X_test4)
y_pred4

NotFittedError: This LogisticRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [428]:
#Verifico la matriz de confusion
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(Y_test4, y_pred4)
print('Matriz de Confusion')
print(matriz)

NameError: name 'y_pred4' is not defined

In [ ]:
#Calculamos la prediccion del modelo
from sklearn.metrics import precision_score
precision = precision_score(Y_test4, y_pred4, average="binary", pos_label="pocas")
print('Precision del modelo:')
print(precision)

In [ ]:
#Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(Y_test4, y_pred4)
print('Exactitud del modelo:')
print(exactitud)

In [ ]:
#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(Y_test4, y_pred4, average="binary", pos_label="pocas")
print('Sensibilidad del modelo:')
print(sensibilidad)